---
- hosts: test

  vars:
    same:   yes
    factor: 1.0

  tasks:
    - set_fact:
        duration: >-
          {%- if same|bool -%}
            {{ factor|float }}
          {%- else -%}
            {{ (inventory_hostname|regex_search('\d+')|int) * factor|float }}
          {%- endif -%}

    - debug:
        msg: >-
          [INFO] {{inventory_hostname}}: Pausing for {{duration}} seconds

    - name: sleep {{duration}} seconds
      command: sleep {{duration}}
      changed_when: false

    - debug:
        msg: >-
          [INFO] {{inventory_hostname}}:
          Done at {{lookup('pipe', 'date +%T')}}
