---
version: 3

dependencies:
  ansible_core:
    package_pip: ansible-core==2.14.16
  ansible_runner:
    package_pip: ansible-runner

  system:
    - openssh-clients

  galaxy:
    collections:
      - name: awx.awx
      - name: ansible.posix
      - name: community.general

images:
  base_image:
    name: quay.io/centos/centos:stream9
