---
- hosts: all

  tasks:
    - name: Check status of firewalld service
      shell: systemctl is-active firewalld.service || true
      register: firewalld_status_cmd
      changed_when: false

    - name: Open HTTP(S) ports, if firewalld is active
      firewalld:
        service: "{{item}}"
        state: enabled
        permanent: yes
        immediate: yes
      with_items: [ http, https ]
      when: firewalld_status_cmd.stdout == "active"
