---
- hosts: localhost

  vars:
    animals:
      - name: Lassie
        type: Dog
      - name: Fido
        type: Dog
      - name: Kitty
        type: Cat


  tasks:
    - debug:
        msg: >-
          {{ animals | map(attribute='name') | join(', ') }}
