---
- hosts: localhost

  vars:
    passwort: Supersecret

  tasks:
    - name: SHA512-hash (random salt)
      debug:
        msg: "{{ passwort | password_hash('sha512') }}"

    - name: SHA512-hash (idempotent)
      debug:
        msg: >-
          {{ passwort |
             password_hash('sha512', 65534   |
             random(seed=inventory_hostname) |
             string) }}
