---
- hosts: debian

  vars:
    users:
      - name: john
        fullname: John Doe
      - name: mary
        fullname: Mary Major
      - name: hans
        fullname: Hans Hansen

  tasks:
    - name: Create user
      user:
        name: "{{item.name}}"
        comment: "{{item.fullname}}"
        shell: /bin/bash
        password: >-
          {{ lookup('password',
                    '/tmp/credentials/pass_'
                    + item.name + '.txt'
                    + ' length=12 encrypt=sha512_crypt') }}
      with_items: "{{users}}"
