---
- name: ansible-bender Playbook
  hosts: all
  vars:
    ansible_bender:
      base_image: "localhost/myhttpd:2.4"
      target_image:
        name: localhost/cgiapp:2.0

  tasks:
    - name: Install python3-flask
      apt:
        update_cache: yes
        name: python3-flask

    - name: Activate modules cgid and rewrite in httpd.conf
      replace:
        path: /usr/local/apache2/conf/httpd.conf
        regexp: '#(LoadModule {{item}}.*)'
        replace: '\1'
      with_items: [cgid, rewrite]

    - name: Copy app
      copy:
        src: app.py
        dest: /usr/local/apache2/cgi-bin
        mode: 0755

    - name: Configure redirect
      blockinfile:
        path: /usr/local/apache2/conf/httpd.conf
        block: |
          RewriteEngine On
          RewriteRule ^/$ /cgi-bin/app.py [NC,PT]
